server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    # Essencial para React Router funcionar (rotas como /admin, /consultor, etc.)
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Cache para assets estáticos (JS, CSS, Imagens)
    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2)$ {
        # NÃO cachear o Service Worker!
        if ($uri ~* "sw\.js$") {
            add_header Cache-Control "no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0";
            expires off;
        }
        
        expires 1y;
        add_header Cache-Control "public, immutable";
    }

    # Configuração para o Manifesto PWA
    location = /manifest.webmanifest {
        add_header Content-Type "application/manifest+json";
        add_header Cache-Control "no-cache";
    }


    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml;
}
